#!/usr/bin/env python3
"""Compose every agent definition from the one place its rules are written.

The rules an agent obeys live in `shared/roles/`, once. The variance between
agents is its frontmatter and nothing else — a name, a description, a model, a
permission block — so that is all a per-agent stub under `shared/roles/agents/`
contains. This script joins the two.

Why a generator at all, when the whole point is not to copy text: Claude Code
has a real include (`skills:` preloads a skill's full body into a subagent at
startup) but OpenCode has none. A markdown agent there has no `prompt:` field —
the body IS the prompt — and `{file:}` substitution belongs to `opencode.json`,
passing through a markdown body as literal text. Both were established by probe
on 1.17.18 with `opencode debug agent`, which resolves an agent without calling
a model. So OpenCode's bodies are composed here, and Claude Code's are not: its
agents carry only their role, and the shared rules reach them through the skill
this script also writes.

Run it after editing anything under `shared/roles/`. `--check` verifies that
what is on disk matches what would be generated, and is what the gate runs.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
ROLES = ROOT / "shared" / "roles"
STUBS = ROLES / "agents"
SKILL = ROOT / "shared" / "skills" / "kit-role-rules" / "SKILL.md"

# The blocks that were byte-identical across nineteen agent files — 836 of the
# 2281 lines in the layer. Which of them an agent carries is recorded per agent
# in agents.json, taken from what that agent already had, so restoring them
# changes no agent's contract.
BLOCK_FILES = {
    "## Proportional execution": "block-proportional-execution.md",
    "## Report budget": "block-report-budget.md",
    "## Delivery contract": "block-delivery-contract.md",
}

BANNER = (
    "<!-- GENERATED by shared/scripts/build-agents.py — do not edit.\n"
    "     Edit shared/roles/ and regenerate; `tests/test_agents_generated.sh`\n"
    "     fails when this file and its sources disagree. -->"
)

SKILL_FRONTMATTER = """---
name: kit-role-rules
description: The rules every kit role obeys — the non-negotiables, proportional execution, the delivery contract, and the report budget and format for roles that report to a delegating session. Preloaded into a worker at startup; not invoked by hand.
---"""


def read(path: pathlib.Path) -> str:
    return path.read_text(encoding="utf-8").strip("\n")


def load_manifest() -> dict:
    return json.loads((ROLES / "agents.json").read_text(encoding="utf-8"))


def skill_body() -> str:
    return "\n\n".join([
        SKILL_FRONTMATTER,
        BANNER,
        "# Role rules",
        *(read(ROLES / f) for f in BLOCK_FILES.values()),
    ]) + "\n"


def agent_body(entry: dict) -> str:
    """One agent file: its own frontmatter and its own text, then the shared
    blocks it used to carry a private copy of.

    The stub holds everything that is genuinely this agent's — its identity and
    whatever its job needs said that no other agent says. Only the blocks that
    were byte-identical across nineteen files were taken out of it, and those
    come back from `shared/roles/` at build time. Nothing an agent said is lost;
    it is just no longer said nineteen times.

    Claude Code receives them through the preloaded skill, so its files end at
    their own text. OpenCode has no include, so its files carry the blocks
    inline.
    """
    key = f"{entry['runtime']}--{entry['name']}"
    stub = read(STUBS / f"{key}.md")
    parts = [stub]

    if entry["runtime"] == "claude":
        # `skills:` is injected rather than stored, so a stub stays a pure
        # record of what the agent already declared.
        if "skills:" not in stub:
            parts[0] = stub.replace("\n---", "\nskills: kit-role-rules\n---", 1)
        parts.insert(1, BANNER)
    else:
        parts.append(BANNER)
        for heading in entry["blocks"]:
            parts.append(read(ROLES / BLOCK_FILES[heading]))

    return "\n\n".join(parts) + "\n"


def targets() -> dict[pathlib.Path, str]:
    out = {SKILL: skill_body()}
    for entry in load_manifest().values():
        out[ROOT / entry["src"]] = agent_body(entry)
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any file differs from what would be generated")
    args = ap.parse_args()

    drift = []
    for path, content in sorted(targets().items()):
        rel = path.relative_to(ROOT)
        if args.check:
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current != content:
                drift.append(rel)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    if args.check:
        if drift:
            print("AGENT DRIFT — these do not match shared/roles/:", file=sys.stderr)
            for rel in drift:
                print(f"  {rel}", file=sys.stderr)
            print("\nRegenerate with: python3 shared/scripts/build-agents.py", file=sys.stderr)
            return 1
        print(f"agents in sync with shared/roles/ ({len(targets())} files)")
        return 0

    print(f"generated {len(targets())} files from shared/roles/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
