#!/usr/bin/env python3
"""Compose every agent definition from the one place its rules are written.

The rules an agent obeys live in `shared/roles/`, once: the text of its role
(`execute.md`, `verify.md`, `review.md`), the non-negotiable rules every role
shares (`common.md`), three shared blocks, and the report format
(`worker-report.md`), and the final-answer checklist
(`reread-checklist.md`). The variance between agents is its frontmatter — a name,
a description, a permission block — plus, for the OpenCode leads that play no
role file, their own text. That is all a per-agent stub under
`shared/roles/agents/` contains. No stub names a model: each agent is rendered
once per budget, into `<runtime>/agents/<budget>/<name>.md`, with the model
`shared/roles/models.json` holds for its runtime, budget and role. This script
joins them.

Why a generator at all, when the whole point is not to copy text: Claude Code
has a real include (`skills:` preloads a skill's full body into a subagent at
startup) but OpenCode has none. A markdown agent there has no `prompt:` field —
the body IS the prompt — and `{file:}` substitution belongs to `opencode.json`,
passing through a markdown body as literal text. Both were established by probe
on 1.17.18 with `opencode debug agent`, which resolves an agent without calling
a model. So OpenCode's bodies are composed here, and Claude Code's are not: its
agents carry only their role, and the shared rules reach them through the skill
this script also writes.

Run it after editing anything under `shared/roles/`, including a refresh of
`models.json`. `--check` verifies that what is on disk matches what would be
generated, and that no other agent file sits beside the renderings; it is what
the gate runs.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
ROLES = ROOT / "shared" / "roles"
STUBS = ROLES / "agents"
MODELS = ROLES / "models.json"
SKILL = ROOT / "shared" / "skills" / "kit-role-rules" / "SKILL.md"
# Where the renderings live, one directory per runtime.
AGENT_DIRS = (ROOT / "claude" / "agents", ROOT / "opencode" / "agents", ROOT / "codex" / "agents")

# The blocks that were byte-identical across nineteen agent files — 836 of the
# 2281 lines in the layer. Which of them an agent carries is recorded per agent
# in agents.json: every role agent carries all three, and the leads none.
BLOCK_FILES = {
    "## Proportional execution": "block-proportional-execution.md",
    "## Report budget": "block-report-budget.md",
    "## Delivery contract": "block-delivery-contract.md",
}

# The role an agent plays is named in agents.json. The roles below have a
# composed text; `plan` and `orchestrate` do not, so the OpenCode leads that play
# them keep their own text in their stubs.
ROLE_FILES = {
    "execute": "execute.md",
    "verify": "verify.md",
    "review": "review.md",
}
CODEX_ROLE_FILES = {**ROLE_FILES, "plan": "plan.md"}
RULES_FILE = "common.md"
REPORT_FILE = "worker-report.md"
REREAD_FILE = "reread-checklist.md"

BANNER = (
    "<!-- GENERATED by shared/scripts/build-agents.py — do not edit.\n"
    "     Edit shared/roles/ and regenerate; `tests/test_agents_generated.sh`\n"
    "     fails when this file and its sources disagree. -->"
)

SKILL_FRONTMATTER = """---
name: kit-role-rules
description: The rules every kit role obeys — the non-negotiables, delivery contract, report format, and final-answer re-read. Preloaded into a worker at startup; not invoked by hand.
---"""


def read(path: pathlib.Path) -> str:
    return path.read_text(encoding="utf-8").strip("\n")


def reread_body() -> str:
    return "\n\n".join([
        "## Final-answer re-read",
        "Before returning any final answer or report, privately check the draft "
        "against every item below. Run an available check that the draft names "
        "but has not performed, then correct the draft. Do not announce this "
        "pass or invoke the operator-only `sc` entry point. Keep required report "
        "headers and fields: for a fixed report schema, put the conclusion or "
        "verdict in its first required field instead of adding a pre-header "
        "Yes/No. The required report format takes precedence where it fixes "
        "the opening line.",
        read(ROLES / REREAD_FILE),
    ])


def load_manifest() -> dict:
    return json.loads((ROLES / "agents.json").read_text(encoding="utf-8"))


def load_models() -> dict:
    """Per runtime and budget, each role's model, as the refresh wrote it."""
    selection = json.loads(MODELS.read_text(encoding="utf-8"))
    return {runtime: {budget: {role: pick["model"] for role, pick in outcome["roles"].items()}
                      for budget, outcome in budgets.items()}
            for runtime, budgets in selection["runtimes"].items()}


def with_model(stub: str, model: str, where: str) -> str:
    """The stub with `model:` added to its frontmatter, after `mode:` when the
    agent has one and after `description:` otherwise."""
    lines = stub.split("\n")
    end = lines.index("---", 1)
    if any(line.startswith("model:") for line in lines[1:end]):
        raise SystemExit(f"{where} names a model; models.json holds every agent's model")
    anchor = next((i for i in range(1, end) if lines[i].startswith("mode:")), None)
    if anchor is None:
        anchor = next(i for i in range(1, end) if lines[i].startswith("description:"))
    lines.insert(anchor + 1, f"model: {model}")
    return "\n".join(lines)


def skill_body() -> str:
    """What every Claude Code role shares: the non-negotiable rules, the three
    blocks and the report format. Each role's own text stays in its agent file."""
    return "\n\n".join([
        SKILL_FRONTMATTER,
        BANNER,
        "# Role rules",
        read(ROLES / RULES_FILE),
        *(read(ROLES / f) for f in BLOCK_FILES.values()),
        read(ROLES / REPORT_FILE),
        reread_body(),
    ]) + "\n"


def agent_body(entry: dict, model: str) -> str:
    """One agent file: its stub with the model for one budget, then the text
    of the role it plays, then what every role shares.

    The stub holds what is genuinely this agent's: its frontmatter, and for a
    lead whose role has no composed text, its own text. A role agent's text is
    its role file, written once for both runtimes.

    Claude Code receives the shared rules, blocks and report format through
    the preloaded skill, so its files end at the role text. OpenCode has no
    include, so its files carry them inline; a lead carries only the blocks
    recorded for it, which today is none.
    """
    key = f"{entry['runtime']}--{entry['name']}"
    stub = with_model(read(STUBS / f"{key}.md"), model, f"shared/roles/agents/{key}.md")
    role = entry.get("role")
    composed = role in ROLE_FILES
    parts = [stub]

    if entry["runtime"] == "claude":
        # `skills:` is injected rather than stored, so a stub stays a pure
        # record of what the agent itself declares.
        if "skills:" not in stub:
            parts[0] = stub.replace("\n---", "\nskills: kit-role-rules\n---", 1)
        parts.append(BANNER)
        if composed:
            parts.append(read(ROLES / ROLE_FILES[role]))
    else:
        parts.append(BANNER)
        if composed:
            parts.append(read(ROLES / ROLE_FILES[role]))
            parts.append(read(ROLES / RULES_FILE))
        for heading in entry["blocks"]:
            parts.append(read(ROLES / BLOCK_FILES[heading]))
        if composed:
            parts.append(read(ROLES / REPORT_FILE))
        parts.append(reread_body())

    return "\n\n".join(parts) + "\n"


def codex_body(entry: dict) -> str:
    key = f"codex--{entry['name']}"
    stub = read(STUBS / f"{key}.md")
    descriptions = [line.partition(":")[2].strip() for line in stub.splitlines()
                    if line.startswith("description:")]
    if len(descriptions) != 1 or "\n---" not in stub:
        raise SystemExit(f"shared/roles/agents/{key}.md needs one description")
    if any(line.startswith("model:") for line in stub.splitlines()):
        raise SystemExit(f"shared/roles/agents/{key}.md names a model")
    role = entry["role"]
    instructions = "\n\n".join([
        read(ROLES / CODEX_ROLE_FILES[role]),
        read(ROLES / RULES_FILE),
        *(read(ROLES / BLOCK_FILES[heading]) for heading in entry["blocks"]),
        read(ROLES / REPORT_FILE),
        reread_body(),
    ]) + "\n"
    fields = [
        "# GENERATED by shared/scripts/build-agents.py — do not edit.",
        f"name = {json.dumps(entry['name'])}",
        f"description = {json.dumps(descriptions[0], ensure_ascii=False)}",
        f"developer_instructions = {json.dumps(instructions, ensure_ascii=False)}",
    ]
    if role in ("review", "verify", "plan"):
        fields.append('sandbox_mode = "read-only"')
    return "\n".join(fields) + "\n"


def targets() -> dict[pathlib.Path, str]:
    out = {SKILL: skill_body()}
    models = load_models()
    for entry in load_manifest().values():
        if entry["runtime"] == "codex":
            out[ROOT / entry["src"]] = codex_body(entry)
            continue
        for budget, roles in models[entry["runtime"]].items():
            out[ROOT / entry["src"].format(budget=budget)] = agent_body(entry, roles[entry["role"]])
    return out


def strays(expected: dict[pathlib.Path, str]) -> list[pathlib.Path]:
    """Agent files under the runtimes' agent directories that no source renders."""
    return sorted(path for base in AGENT_DIRS if base.is_dir()
                  for path in base.rglob("*.toml" if base.name == "agents" and base.parent.name == "codex" else "*.md")
                  if path not in expected)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any file differs from what would be generated")
    args = ap.parse_args()

    expected = targets()
    drift = []
    for path, content in sorted(expected.items()):
        rel = path.relative_to(ROOT)
        if args.check:
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current != content:
                drift.append(rel)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    stray = strays(expected)
    if args.check:
        if drift or stray:
            if drift:
                print("AGENT DRIFT — these do not match shared/roles/:", file=sys.stderr)
                for rel in drift:
                    print(f"  {rel}", file=sys.stderr)
            if stray:
                print("NOT RENDERED — no source in shared/roles/ produces these:", file=sys.stderr)
                for path in stray:
                    print(f"  {path.relative_to(ROOT)}", file=sys.stderr)
            print("\nRegenerate with: python3 shared/scripts/build-agents.py", file=sys.stderr)
            return 1
        print(f"agents in sync with shared/roles/ ({len(expected)} files)")
        return 0

    for path in stray:
        path.unlink()
        print(f"removed {path.relative_to(ROOT)}: no source in shared/roles/ renders it")
    print(f"generated {len(expected)} files from shared/roles/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
